spring:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: logs/community.log
    max-size: 100MB
    max-history: 15
  level:
    com.xbc.community.mapper : debug
    root: info

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
server:
  port: 8888
