spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.xbc.community.mapper : debug
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
